### ISSUE TITLE
How to make inline formulas

### ISSUE THREAD

**Issue by Yamioni2007** [justforuse/vue-mathjax-next#18]
Is there a possibility to prevent the linebreaks before and after the formula? My code looks like this:
```
<div>
      I would like to have the formula <vue-mathjax :formula="'$$\\frac{1}{2} \\cdot x^2$$'" /> in the text without any linebreaks
</div>
```
but this always display the formula in a separate line. 
thanks in advance

**Comment by Yamioni2007** [comment]
Nevermind, I figured it out by my self 😅

This isn't about your repo, this is about Mathjax. with only one $ it works. So for all who only know latex like me, this is the solution:
```
<div>
      This formula <vue-mathjax :formula="'$\\frac{1}{2} \\cdot x^2$'" /> is in the text 
</div>
```

**Comment by justforuse** [comment]
👍
